apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - ../../base/notifications
configurations:
  - kustomizeconfig.yaml
configMapGenerator:
  - name: notification-values
    behavior: merge
    files:
      - values.yaml=values.yaml