apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Alert
metadata:
  name: on-call-errors
spec:
  providerRef: 
    name: sns
  eventSeverity: error
  eventSources:
    - kind: HelmRelease
      name: '*'
    - kind: GitRepository
      name: '*'
  suspend: false