apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Alert
metadata:
  name: on-call-info
spec:
  providerRef: 
    name: sns
  eventSeverity: info
  eventSources:
    - kind: GitRepository
      name: '*'
  suspend: false