apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: podinfo-frontend
  namespace: argocd
spec:
  project: default
  source:
    chart: podinfo/podinfo
    repoURL:  https://stefanprodan.github.io/podinfo
    targetRevision: 6.1.3
    helm:
      releaseName: frontend
  destination:
    server: "https://kubernetes.default.svc"
    namespace: podinfo