apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - release.yaml
configMapGenerator:
  - name: notification-values
    files:
      - values.yaml=values.yaml
configurations:
  - kustomizeconfig.yaml
