apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: notifications
spec:
  interval: 5m
  chart:
    spec:
      chart: ./infrastructure/base/charts/cluster-notifications
      sourceRef:
        kind: GitRepository
        name: flux-system
      interval: 1m
  valuesFrom:
    - kind: ConfigMap
      name: notification-values